"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%jw14%dnklc^=u=c0fyqhuxt7y8us5hfmhz#5ukn3(&x=n68*h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ["127.0.0.1"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "user",
    "todo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "user.context_processors.constant_data",  # コンテキストプロセッサーを追加
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "django_db",
        "USER": "postgres",
        "PASSWORD": "postgres",
        "HOST": "db",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Django のパスワードハッシュ化とバリデーション設定

# パスワードのハッシュ化設定（上から順番に試行される）
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",  # 最も強力なハッシュ化アルゴリズム（ライブラリのインストールが必要）
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",  # 安全性の高いハッシュアルゴリズム
    "django.contrib.auth.hashers.BCryptPasswordHasher",  # BCrypt の SHA256 なしバージョン
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",  # Django のデフォルトのハッシュアルゴリズム（比較的安全）
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",  # SHA1 を使用した PBKDF2（非推奨）
]

# パスワードのバリデーションルール設定
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # ユーザー名やメールアドレスと類似したパスワードの使用を禁止
        # 例: ユーザー名が "tom" の場合、"tom123" のようなパスワードは不可
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,  # パスワードの最低文字数を 8 に設定（8 文字以上でなければならない）
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        # 一般的に使われるパスワード（例: "12345678", "password"）の使用を禁止
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        # 数字のみのパスワードの使用を禁止（例: "12345678" は不可）
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_DIR = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_DIRS = [
    STATIC_DIR,
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ユーザーモデルを指定する
AUTH_USER_MODEL = "user.User"

# APPのタイトルを指定する
APP_TITLE = "ユーザー管理システム"

# LOGIN_URL = '/user/login'
# LOGIN_REDIRECT_URL = '/user/user'   # ログイン後ホームページに遷移する
# LOGOUT_REDIRECT_URL = '/user/user'  # ログアウト後ホームページに遷移する

# メッセージ格納域
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# メッセージタグ
MESSAGE_TAGS = {
    message_constants.DEBUG: "debug",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    message_constants.ERROR: "danger",
}

# セッション保存時間
SESSION_COOKIE_AGE = 60 * 60
