# Generated by Django 4.2.11 on 2025-01-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_phone_number",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("phone_number", None), _negated=True),
                    models.Q(("phone_number", ""), _negated=True),
                ),
                fields=("phone_number",),
                name="unique_phone_number",
            ),
        ),
    ]
